export const keywordMap: Record<string, string[]> = {
  company_count: [
    'how many companies',
    'companies visited',
    'total companies',
    'number of companies',
    'how many firms',
    'companies came',
    'companies visited campus',
  ],
  where_applied: [
    'where did i apply',
    'which companies did i apply',
    'list my applications',
    'show my applications',
    'where have i applied',
    'applied companies',
    'my applications',
  ],
  shortlist_status: [
    'shortlisted',
    'was i shortlisted',
    'am i shortlisted',
    'shortlist status',
    'did i get shortlisted',
    'got shortlisted',
  ],
  // Change 2 fix: removed bare 'offer' and 'selected' which confused with package_query
  offer_status: [
    'did i get an offer',
    'do i have an offer',
    'did i get selected',
    'got selected',
    'did i receive an offer',
    'have i received an offer',
    'placement result',
    'am i selected',
    'was i selected',
  ],
  // Change 2 fix: strengthened with salary/amount-specific terms, removed 'my offer package'
  package_query: [
    'package',
    'salary',
    'ctc',
    'how much salary',
    'what is my package',
    'my salary',
    'compensation',
    'stipend',
    'how much ctc',
    'what ctc',
    'lpa',
    'lakh',
  ],
  application_status: [
    'application status',
    'status of my application',
    'where am i',
    'pipeline',
    'current stage',
    'interview stage',
    'applied status',
    'show status',
  ],
  // Change 1: NEW intent — placed or not placed outcome
  placement_outcome: [
    'am i placed',
    'have i been placed',
    'did i get placed',
    'am i a placed student',
    'placement outcome',
    'am i finally placed',
    'got placed',
    'placement confirmed',
    'have i got placed',
    'tell me if i am placed',
    'am i through',
    'placement done',
  ],
};

export const CONFIDENCE_THRESHOLD = 0.05;
