export const keywordMap: Record<string, string[]> = {
  company_count: [
    'how many companies',
    'companies visited',
    'total companies',
    'number of companies',
    'how many firms',
    'companies came',
    'companies visited campus',
    'count of companies',
    'list of companies',
    'companies recruiting',
    'how many drives',
    'total drives',
    'companies coming',
    'firms recruiting',
    'number of drives',
    'drives scheduled',
    'firms visiting',
    'recruiting',
  ],
  where_applied: [
    'where did i apply',
    'which companies did i apply',
    'list my applications',
    'show my applications',
    'where have i applied',
    'applied companies',
    'my applications',
    'what did i apply for',
    'companies i applied to',
    'tell me my applications',
    'drives i applied to',
    'applications i submitted',
    'drives i submitted',
    'which companies have i applied',
  ],
  shortlist_status: [
    'shortlisted',
    'was i shortlisted',
    'am i shortlisted',
    'shortlist status',
    'did i get shortlisted',
    'got shortlisted',
    'have i been shortlisted',
    'show shortlist',
    'where am i shortlisted',
    'shortlisted drives',
    'made it to shortlist',
    'made it to the shortlist',
  ],
  offer_status: [
    'did i get an offer',
    'do i have an offer',
    'did i get selected',
    'got selected',
    'did i receive an offer',
    'have i received an offer',
    'placement result',
    'am i selected',
    'was i selected',
    'offer received',
    'any offers',
    'show my offers',
    'did any company select me',
    'offer details',
  ],
  package_query: [
    'package',
    'salary',
    'ctc',
    'how much salary',
    'what is my package',
    'my salary',
    'compensation',
    'stipend',
    'how much ctc',
    'what ctc',
    'lpa',
    'lakh',
    'what is my ctc',
    'how much will i earn',
    'package details',
    'pay details',
    'my earnings',
  ],
  application_status: [
    'application status',
    'status of my application',
    'where am i',
    'pipeline',
    'current stage',
    'interview stage',
    'applied status',
    'show status',
    'track my application',
    'application progress',
    'where do i stand',
    'my drive status',
  ],
  placement_outcome: [
    'am i placed',
    'have i been placed',
    'did i get placed',
    'am i a placed student',
    'placement outcome',
    'am i finally placed',
    'got placed',
    'placement confirmed',
    'have i got placed',
    'tell me if i am placed',
    'am i through',
    'placement done',
    'placed or not',
    'did i secure placement',
    'final placement status',
    'secure a placement',
    'secured placement',
  ],
};

export const CONFIDENCE_THRESHOLD = 0.05;
